export const products = [
  {
    title: "Lorem, ipsum dolor",
    alt: "Image-1",
    availability: "in-stock",
    points: 1.5 / 5,
    style: "sport",
    lifestyle: "lifestyle",
  },
  {
    title: "Lorem, ipsum dolor",
    alt: "Image-1",
    availability: "out-stock",
    points: 3.4 / 5,
    style: "Casual",
    lifestyle: "lifestyle",
  },
  {
    title: "Lorem, ipsum dolor",
    alt: "Image-1",
    availability: "out-stock",
    points: 0.5 / 5,
    style: "sport",
    lifestyle: "lifestyle",
  },
  {
    title: "Lorem, ipsum dolor",
    alt: "Image-1",
    availability: "in-stock",
    points: 1 / 5,
    style: "Casual",
    lifestyle: "lifestyle",
  },
  {
    title: "Lorem, ipsum dolor",
    alt: "Image-1",
    availability: "in-stock",
    points: 2.5 / 5,
    style: "Casual",
    lifestyle: "lifestyle",
  },
  {
    title: "Lorem, ipsum dolor",
    alt: "Image-1",
    availability: "out-stock",
    points: 4.9 / 5,
    style: "sport",
    lifestyle: "lifestyle",
  },
];
